config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post
  after_save :update_comments_count
  after_destroy :decrease_comments_count

  validates :text, presence: true, length: { in: 2..100 }

  def update_comments_count
    post.increment!(:comments_count)
  end

  def decrease_comments_count
    post.decrement!(:comments_count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post
  after_save :update_likes_count
  after_destroy :decrease_likes_count

  def update_likes_count
    post.increment!(:likes_count)
  end

  def decrease_likes_count
    post.decrement!(:likes_count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments, dependent: :destroy, foreign_key: :post_id
  has_many :likes, dependent: :destroy, foreign_key: :post_id
  after_save :update_posts_count
  after_destroy :decrease_posts_count

  attribute :comments_count, :integer, default: 0
  attribute :likes_count, :integer, default: 0

  validates :title, presence: true, length: { in: 2..250 }
  validates :text, presence: true, length: { in: 2..600 }
  validates :comments_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.includes(:author).order(created_at: :asc).limit(5)
  end

  def update_posts_count
    author.increment!(:posts_count)
  end

  def decrease_posts_count
    author.decrement!(:posts_count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, dependent: :destroy, foreign_key: :author_id
  has_many :comments
  has_many :likes

  attribute :posts_count, :integer, default: 0

  validates :name, presence: true, length: { minimum: 2 }
  validates :bio, presence: true, length: { in: 2..250 }
  validates :posts_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.includes(:author).order(created_at: :asc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name photo bio])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name photo bio])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    @comment.post = Post.find(params[:post_id])

    if @comment.save
      redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @like.author = current_user
    @like.post = Post.find(params[:post_id])
    @like.save!
    redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments, :likes, :author)
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:author)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    if @post.save
      redirect_to user_posts_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(id: :asc)
  end

  def show
    @user = User.find(params[:id])
    @recent_posts = @user.recent_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<section class='flex_column'>
  <div>
    <h2>Add a Comment</h2>
    <%= render "shared/comment", comment: @comment %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogAppRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <%= render "shared/userslinks" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<section class='flex_column'>
  <div class='flex space_btw mb_1_5em'>
    <%= render "shared/user", user: @user %>
  </div>
  <div class='flex_column gap_3em'>
    <% @posts.each do |post| %>
      <%= link_to user_post_path(post.author, post), class: 'flex_column' do %>
        <div class='pad_1em flex_column border_solid mb_0_2em'>
          <%= render "shared/post_info", post: post %>
        </div>
        <%= render "shared/post_comments", comments: post.recent_comments %>
      <% end %>
    <% end %>
  </div>
  <a class='border_solid pad_0_5em as_center color_black mt_2em' href="#">Pagination</a>
</section>

app/views/posts/new.html.erb
<section class='flex_column'>
  <div>
    <h2>New Post</h2>
    <%= render "shared/form", post: @post %>
  </div>
</section>

app/views/posts/show.html.erb
<section class='flex_column'>
  <div class='pad_1em flex_column border_solid mb_0_2em'>
    <div class='flex space_btw'>
      <h3 class='mb_1em'>Post #<%= @post.id %> <%= @post.title %></h3>
      <span>Comments: <%= @post.comments_count %>, Likes: <%= @post.likes_count %></span>
    </div>
    <p><%= @post.text %></p>
    <div class='flex gap_1em'>
      <%= render partial: "shared/like", locals: { like: Like.new, post_id: @post.id, user_id: @post.author } %>
      <%= link_to "Add a comment 📝", new_user_post_comment_path(@post.author, @post), class: 'color_black border_solid width_auto font_size_0_5em as_center' %>
    </div>
  </div>
  <%= render "shared/post_comments", comments: @comments %>
</section>

app/views/shared/_comment.html.erb
<%= form_with model: comment, url: user_post_comments_path  do |form| %>
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/shared/_form.html.erb
<%= form_with model: post, url: user_posts_path do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% post.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :text %><br>
    <%= form.text_area :text %><br>
    <% post.errors.full_messages_for(:text).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shared/_like.html.erb
<%= form_with(model: like, url: user_post_likes_path(user_id: @post.author, post_id: @post), local: true) do |form| %>
  <%= form.submit "Like ❤️" %>
<% end %>

app/views/shared/_post_comments.html.erb
<% if comments.any? %>
  <div class='pad_1em flex_column border_solid'> 
    <% comments.each do |comment| %>
      <p class='color_black'><%= comment.author.name %>: <span> <%= comment.text %> </span> </p>
    <% end %>
  </div>
<% else %>
  <div class='pad_1em flex_column border_solid'>
    <p class='color_black'>There are no comments</p>
  </div>
<% end %>

app/views/shared/_post_info.html.erb
<h3 class='mb_1em color_black'>Post #<%= post.id %> <%= post.title %></h3>
<p class='color_black'><%= post.text %></p>
<span class='color_black as_flex_end'>Comments: <%= post.comments_count %>, Likes: <%= post.likes_count %></span>

app/views/shared/_recent_posts.html.erb
<% if recent_posts.any? %>
  <div>
    <% recent_posts.each do |post| %>
      <%= link_to user_post_path(post.author, post), class: 'pad_1em flex_column border_solid mb_1em' do %>
        <%= render "shared/post_info", post: post %>
      <% end %>
    <% end %>
  </div>
  <div class='flex gap_3em center'>
  <%= link_to "See all posts", user_posts_path(user), class: 'border_solid pad_0_5em color_black' %>
  <%= link_to "New post", new_user_post_path(user), class: 'border_solid pad_0_5em color_black' %>
  </div>
<% else %>
  <p class="text">There are no Posts</p>
<% end %>

app/views/shared/_user.html.erb
<% if user.photo.present? %>
  <%= image_tag(user.photo, alt: 'User photo', size: "200x150", class: 'width_15 border_solid') %>
<% else %>
  <%= image_tag('photo.png', alt: 'User photo', size: "200x150", class: 'width_15 border_solid') %>
<% end %>
<div class='flex space_btw border_solid width_80 ai_center pad_2_5em'>
  <h2 class='font_w_700 font_size_2em color_black'>User name: <%= user.name %></h2>
  <p class='as_flex_end color_black font_size_1_3em'>Number of posts: <%= user.posts_count %></p>
</div>

app/views/shared/_userslinks.html.erb
<div class='flex pad_5x2em flex_end gap_1em'>
  <% if user_signed_in?  %>
    <%= link_to "Edit profile", edit_user_registration_path, class: 'btn secundary-text' %>
    <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'btn secundary-text'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, class: 'btn secundary-text'  %>
    <%= link_to "Login", new_user_session_path, class: 'btn secundary-text' %>
  <% end %>
</div>

app/views/users/index.html.erb
<section>
  <ul class='flex_column gap_3em'>
    <% @users.each do |user| %>
      <li>
        <%= link_to user_path(user), class: 'flex space_btw' do %>
          <%= render "shared/user", user: user %>
        <% end %>
      </li>
    <% end %>
  </ul>
</section>

app/views/users/show.html.erb
<section class='flex_column'>
  <div class='flex space_btw mb_1_5em'>
    <%= render "shared/user", user: @user %>
  </div>
  <div class='flex_column border_solid pad_1em mb_2em'>
    <h3 class='mb_1em font_size_1_5em'>Bio</h3>
    <p class='font_size_1_3em'><%= @user.bio %></p>
  </div>
  <%= render "shared/recent_posts", recent_posts: @recent_posts, user: @user %>
</section>